version: '3'
services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_USER: user 
      MYSQL_ROOT_USER: root 
      MYSQL_PASSWORD: password 
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
    driver: local
